# Generated by Django 6.0.3 on 2026-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('conversation_starter', 'Conversation Starter'), ('activity_prompt', 'Activity Prompt'), ('member_highlight', 'Member Highlight'), ('challenge_post', 'Challenge Post')], max_length=32)),
                ('payload', models.JSONField(default=dict)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('executed', 'Executed'), ('failed', 'Failed')], default='pending', max_length=16)),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
    ]
