# Generated by Django 6.0.3 on 2026-03-15 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('squads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentaction',
            name='squad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_actions', to='squads.squad'),
        ),
    ]
