# Generated by Django 6.0.3 on 2026-03-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('general', '# general'), ('help', '# help')], db_index=True, default='general', max_length=32),
        ),
    ]
