# Generated by Django 6.0.3 on 2026-03-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='communication_style',
            field=models.CharField(blank=True, choices=[('fast_discussion', 'Fast Discussion'), ('deep_analysis', 'Deep Analysis'), ('casual_chat', 'Casual Chat')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='intent',
            field=models.CharField(blank=True, choices=[('learn', 'Learn'), ('build', 'Build'), ('collaborate', 'Collaborate'), ('explore', 'Explore')], default='', max_length=16),
        ),
        migrations.AddField(
            model_name='profile',
            name='onboarding_complete',
            field=models.BooleanField(default=False),
        ),
    ]
